target_include_directories(ae PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

set(AE_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)
file(GLOB AE_SRC CONFIGURE_DEPENDS ${AE_SRC_DIR}/*.c*)
file(GLOB AE_NODE_COMP_SRC CONFIGURE_DEPENDS ${AE_SRC_DIR}/node/components/*.c*)

target_sources(
  ae PRIVATE
  ${AE_SRC_DIR}/node/node.cc
  ${AE_SRC}
  ${AE_NODE_COMP_SRC}
)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/vendor)
include(${CMAKE_SOURCE_DIR}/cmake/CPM.cmake)

CPMAddPackage(
  NAME raylib
  GITHUB_REPOSITORY raysan5/raylib
  GIT_TAG 6.0
  GIT_SHALLOW TRUE
)

target_compile_definitions(
  raylib PRIVATE
  SUPPORT_FILEFORMAT_JPG=1
  SUPPORT_MODULE_RAUDIO=0
  SUPPORT_TRACELOG=0
  SUPPORT_SCREEN_CAPTURE=0
  SUPPORT_CAMERA_SYSTEM=0
  SUPPORT_GESTURES_SYSTEM=0
  SUPPORT_RPRAND_GENERATOR=0
  SUPPORT_WINMM_HIGHRES_TIMER=0
  SUPPORT_CLIPBOARD_IMAGE=0
  SUPPORT_FILEFORMAT_OBJ=0
  SUPPORT_FILEFORMAT_MTL=0
  SUPPORT_FILEFORMAT_IQM=0
  SUPPORT_FILEFORMAT_GLTF=0
  SUPPORT_FILEFORMAT_VOX=0
  SUPPORT_FILEFORMAT_M3D=0
  SUPPORT_MESH_GENERATION=0
)

# maybe todo: just vendor lua?
CPMAddPackage(
  NAME lua
  GITHUB_REPOSITORY lua/lua
  GIT_TAG v5.4.8
  GIT_SHALLOW TRUE
)

add_library(lua STATIC)

file(GLOB LUA_HEADERS ${lua_SOURCE_DIR}/*.h)
file(GLOB LUA_SRC ${lua_SOURCE_DIR}/*.c)

list(
  REMOVE_ITEM LUA_SRC
  ${lua_SOURCE_DIR}/lua.c
  ${lua_SOURCE_DIR}/onelua.c
)

target_include_directories(lua PUBLIC ${lua_SOURCE_DIR})
target_sources(lua PRIVATE ${LUA_SRC})

set(SOL2_BUILD_LUA OFF)
set(SOL2_LUA_VERSION "5.4.8")

CPMAddPackage(
  NAME sol2
  GITHUB_REPOSITORY ThePhD/sol2
  GIT_TAG v3.5.0
  GIT_SHALLOW TRUE
)

CPMAddPackage(
  NAME fmt
  GITHUB_REPOSITORY fmtlib/fmt
  GIT_TAG 12.1.0
  GIT_SHALLOW TRUE
)

target_link_libraries(ae PUBLIC raylib lua sol2::sol2)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/modules)