#pragma once

#if defined(AETHER_ENGINE_DEBUG) || defined(AETHER_ENGINE_RELWITHDEB)
	#define AETHER_ENGINE_HAS_DEBUG 1
#endif

#define AETHER_ENGINE_VERSION_MAJOR 0
#define AETHER_ENGINE_VERSION_MINOR 0
#define AETHER_ENGINE_VERSION_PATCH 1
#define AETHER_ENGINE_VERSION_STR   "v0.0.1"