name: Build AetherEngine

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.cmake_preset }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Windows
            runner: windows-latest
            cmake_preset: aether-debug

          - os: Windows
            runner: windows-latest
            cmake_preset: aether-debug-verbose

          - os: Windows
            runner: windows-latest
            cmake_preset: aether-release

          - os: Linux
            runner: ubuntu-latest
            cmake_preset: aether-debug

          - os: Linux
            runner: ubuntu-latest
            cmake_preset: aether-debug-verbose

          - os: Linux
            runner: ubuntu-latest
            cmake_preset: aether-release

          - os: macOS
            runner: macos-latest
            cmake_preset: aether-debug

          - os: macOS
            runner: macos-latest
            cmake_preset: aether-debug-verbose

          - os: macOS
            runner: macos-latest
            cmake_preset: aether-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          MAJOR=$(sed -n 's/^[[:space:]]*set(AETHER_VERSION_MAJOR[[:space:]]\+\([0-9]\+\)).*$/\1/p' cmake/version.cmake)
          MINOR=$(sed -n 's/^[[:space:]]*set(AETHER_VERSION_MINOR[[:space:]]\+\([0-9]\+\)).*$/\1/p' cmake/version.cmake)
          PATCH=$(sed -n 's/^[[:space:]]*set(AETHER_VERSION_PATCH[[:space:]]\+\([0-9]\+\)).*$/\1/p' cmake/version.cmake)
          echo "version=${MAJOR}.${MINOR}.${PATCH}" >> $GITHUB_OUTPUT
        
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev

      - name: Configure CMake
        run: cmake --preset ${{ matrix.cmake_preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.cmake_preset }}
        
      - name: Upload artifact
        if: contains(matrix.cmake_preset, 'release')
        uses: actions/upload-artifact@v4
        with:
          name: aether-v${{ steps.version.outputs.version }}-${{ matrix.os }}
          path: build/${{ matrix.cmake_preset }}/bin